 const nameToUrl = {
            "Robin & Dagny": "https://www.facebook.com/robinthomastango",
            "Roxana & Cesar": "https://youtu.be/6wZbMCAeGGk?si=glY3ONv8d-DBEXMh",
            "Cesar": "https://youtu.be/6wZbMCAeGGk?si=glY3ONv8d-DBEXMh",
            "Paloma & Maxi": "http://www.palomaymaximiliano.com",
            "Cecilia Gonzalez": "https://tangomotion.com",
            "Celina & Hugo": "https://hugoandcelina.com/",
            "Celina": "https://hugoandcelina.com/",
            "Florencia & Marcos": "http://www.marcosyflorencia.com/",
            "DJ Avik": "http://www.a2tango.com/teachers.html",
            "DJ Koichiro": "https://www.pghtango.com/about-pgh-tango",
            "DJ Brick": "https://www.facebook.com/brick.robbins",
            "DJ Victoria": "https://www.facebook.com/victoria.randlett",
            "DJ Alex Krebs": "https://www.tangoberretin.com/alexkrebs",
            "DJ Steve Correl": "https://www.facebook.com/steve.correl.1/",
            "DJ Stephen Brady": "https://www.facebook.com/stephen.brady/",
            "DJ Andy Stein": "https://www.facebook.com/andris.stein/",
            "DJ Robin": "http://robinthomastango.com/w/robin/",
            "DJ Rob M": "https://www.facebook.com/rob.montango",
            "DJ Michael D": "https://www.facebook.com/michael.daniels.337582"
        };